$terminal = kitty

#shortcuts
bind = SUPER, RETURN, exec, $terminal
bind = SUPER, Q, killactive
bind = SUPER SHIFT, M, exit
bind = SUPER, F, exec, firefox
bind = SUPER, E, exec, kitty -e nano ~/.config/hypr/hyprland.conf

#navegar entre ventanas
bind = SUPER, left, movefocus, l
bind = SUPER, right, movefocus, r
bind = SUPER, up, movefocus, u
bind = SUPER, down, movefocus, d

#movimiento entre ventanas
bind = SUPER SHIFT, left, movewindow, l
bind = SUPER SHIFT, right, movewindow, r
bind = SUPER SHIFT, up, movewindow, u
bind = SUPER SHIFT, down, movewindow, d

#ratio de ventanas
bind = SUPER CTRL, left, resizeactive, -50 0
bind = SUPER CTRL, right, resizeactive, 50 0

bind = SUPER CTRL, up, resizeactive, 0 -50
bind = SUPER CTRL, down, resizeactive, 0 50

#orientacion entre ventanas

bind = SUPexec-once = $terminal

#cambiar workspace
bind = SUPER, 1, workspace, 1
bind = SUPER, 2, workspace, 2
bind = SUPER, 3, workspace, 3
bind = SUPER, 4, workspace, 4

#mover ventanas entre workspaces
bind = SUPER SHIFT, 1, movetoworkspace, 1
bind = SUPER SHIFT, 2, movetoworkspace, 2
bind = SUPER SHIFT, 3, movetoworkspace, 3
bind = SUPER SHIFT, 4, movetoworkspace, 4

#layout del teclado
input {
    kb_layout = latam
}

dwindle {
    preserve_split = true
}ER, J, layoutmsg, togglesplit

#iniciar una vez automatico al iniciar el sistema
